name : First Workflow
on : [push]
jobs : 
    run-shell-commands:
        runs-on : ubuntu-latest
        steps:
            - name : echo a string
              run : echo "Hello World" 
            - name : Multiline commands
              run : |
                 node -v
                 npm -v   
    parallel-macos-commands:
        runs-on : macos-latest
        steps:
            - name : view softwate version
              run : sw_vers

    dependent-job:
        runs-on : windows-latest
        needs : run-shell-commands
        steps:
            - name : echo string
              run : Write-Output "Windows machine"
            - name : error display
              run : something skip         